"""empty message

Revision ID: 2997d793575
Revises: 51e2c29ad95
Create Date: 2019-09-23 02:52:22.631711

"""

# revision identifiers, used by Alembic.
revision = '2997d793575'
down_revision = '51e2c29ad95'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
